name 'adaptavist-replication'
version '0.3.10'
source 'https://github.com/Adaptavist/puppet-replication.git'
author 'adaptavist'
summary 'replication Module' 
license 'Apache2'
description 'The **replication** module sets up replication between servers. Supported replication modes are filesystem, database and svn'
project_page 'https://github.com/Adaptavist/puppet-replication/browse'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.4.0'
dependency 'duritong//subversion'
dependency 'adaptavist/stunnel_config'
dependency 'adaptavist/lsyncd'
dependency 'adaptavist/rsync_config'
dependency 'puppetlabs/rsync'
